const sampleProducts =  [
  {
    title: "Logitech Wireless Mouse M185",
    category: "electronics",
    mrp: 999,
    sellingPrice: 799,
    summary: "Compact, durable wireless mouse with long battery life.",
    rating: 4.5,
    reviewsCount: 102,
    image: "https://m.media-amazon.com/images/I/61LtuGzXeaL._SL1500_.jpg",
    altText: "Logitech M185 wireless mouse",
    slug: "logitech-wireless-mouse-m185"
  },
  {
    title: "Atomic Habits by James Clear",
    category: "books",
    mrp: 599,
    sellingPrice: 419,
    summary: "A guide to building good habits and breaking bad ones.",
    rating: 4.8,
    reviewsCount: 875,
    image: "https://m.media-amazon.com/images/I/91bYsX41DVL.jpg",
    altText: "Atomic Habits book cover",
    slug: "atomic-habits-james-clear"
  },
  {
    title: "Adidas Men’s Running Shoes",
    category: "fashion",
    mrp: 3499,
    sellingPrice: 2299,
    summary: "Lightweight, breathable shoes designed for comfort and performance.",
    rating: 4.2,
    reviewsCount: 215,
    image: "https://m.media-amazon.com/images/I/71oD5T2XWzL._SL1500_.jpg",
    altText: "Adidas running shoes for men",
    slug: "adidas-mens-running-shoes"
  },
  {
    title: "Prestige Non-Stick Fry Pan",
    category: "home",
    mrp: 1249,
    sellingPrice: 899,
    summary: "Durable non-stick fry pan suitable for all cooktops.",
    rating: 4.3,
    reviewsCount: 85,
    image: "https://m.media-amazon.com/images/I/71ZyE6z2X-L._SL1500_.jpg",
    altText: "Prestige non-stick fry pan",
    slug: "prestige-non-stick-fry-pan"
  },
  {
    title: "Samsung 25W USB-C Charger",
    category: "electronics",
    mrp: 1999,
    sellingPrice: 1299,
    summary: "Fast charging wall adapter compatible with most USB-C devices.",
    rating: 4.6,
    reviewsCount: 350,
    image: "https://m.media-amazon.com/images/I/51zUbui+gbL._SL1000_.jpg",
    altText: "Samsung USB-C charger 25W",
    slug: "samsung-25w-usb-c-charger"
  },
  {
    title: "The Psychology of Money by Morgan Housel",
    category: "books",
    mrp: 499,
    sellingPrice: 349,
    summary: "Timeless lessons on wealth, greed, and happiness.",
    rating: 4.7,
    reviewsCount: 640,
    image: "https://m.media-amazon.com/images/I/71g2ednj0JL.jpg",
    altText: "The Psychology of Money book cover",
    slug: "psychology-of-money-morgan-housel"
  },
  {
    title: "Nike Men’s Sports T-Shirt",
    category: "fashion",
    mrp: 1299,
    sellingPrice: 999,
    summary: "Comfortable Dri-FIT performance tee for workouts and training.",
    rating: 4.4,
    reviewsCount: 178,
    image: "https://m.media-amazon.com/images/I/51dJg7FVYBL._UL1500_.jpg",
    altText: "Nike men's Dri-FIT t-shirt",
    slug: "nike-mens-sports-tshirt"
  },
  {
    title: "Philips LED Bulb 12W Pack of 2",
    category: "home",
    mrp: 349,
    sellingPrice: 259,
    summary: "Energy-efficient LED bulbs with high brightness and long life.",
    rating: 4.5,
    reviewsCount: 900,
    image: "https://m.media-amazon.com/images/I/51aLkQ9RZ1L._SL1000_.jpg",
    altText: "Philips LED bulbs 12W",
    slug: "philips-led-bulb-12w-pack"
  },
  {
    title: "boAt Rockerz 450 Wireless Headphones",
    category: "electronics",
    mrp: 3999,
    sellingPrice: 1499,
    summary: "Powerful bass, 15-hour battery life, and comfortable fit.",
    rating: 4.1,
    reviewsCount: 1052,
    image: "https://m.media-amazon.com/images/I/61u48FEsxOL._SL1500_.jpg",
    altText: "boAt Rockerz 450 headphones",
    slug: "boat-rockerz-450-wireless"
  },
  {
    title: "Ikigai: The Japanese Secret to a Long and Happy Life",
    category: "books",
    mrp: 550,
    sellingPrice: 350,
    summary: "Discover the secrets to living a purposeful and fulfilling life.",
    rating: 4.6,
    reviewsCount: 810,
    image: "https://m.media-amazon.com/images/I/81QpkIctqPL.jpg",
    altText: "Ikigai book cover",
    slug: "ikigai-japanese-secret"
  },
  {
    title: "Men’s Slim Fit Cotton Casual Shirt",
    category: "fashion",
    mrp: 1799,
    sellingPrice: 999,
    summary: "Comfortable and stylish slim-fit shirt for casual wear.",
    rating: 4.2,
    reviewsCount: 230,
    image: "https://m.media-amazon.com/images/I/61z3P6Cr+ML._UL1500_.jpg",
    altText: "Men's casual slim-fit shirt",
    slug: "mens-slim-fit-cotton-shirt"
  },
  {
    title: "Milton Thermosteel Flask 1 Litre",
    category: "home",
    mrp: 1299,
    sellingPrice: 999,
    summary: "Keeps beverages hot or cold for up to 24 hours.",
    rating: 4.4,
    reviewsCount: 520,
    image: "https://m.media-amazon.com/images/I/51JfJtlGhvL._SL1500_.jpg",
    altText: "Milton thermosteel flask 1L",
    slug: "milton-thermosteel-flask-1l"
  },
  {
    title: "Zebronics USB Keyboard and Mouse Combo",
    category: "electronics",
    mrp: 999,
    sellingPrice: 749,
    summary: "Ergonomic keyboard and optical mouse combo for everyday use.",
    rating: 4.0,
    reviewsCount: 110,
    image: "https://m.media-amazon.com/images/I/61vDyJ7EdvL._SL1500_.jpg",
    altText: "Zebronics keyboard and mouse combo",
    slug: "zebronics-keyboard-mouse-combo"
  },
  {
    title: "Rich Dad Poor Dad by Robert Kiyosaki",
    category: "books",
    mrp: 399,
    sellingPrice: 275,
    summary: "A bestselling classic on personal finance and investing mindset.",
    rating: 4.5,
    reviewsCount: 1085,
    image: "https://m.media-amazon.com/images/I/81bsw6fnUiL.jpg",
    altText: "Rich Dad Poor Dad book cover",
    slug: "rich-dad-poor-dad-kiyosaki"
  },
  {
    title: "Solimo Microfiber Single Bedsheet Set",
    category: "home",
    mrp: 899,
    sellingPrice: 499,
    summary: "Soft and durable microfiber bedsheet with matching pillow cover.",
    rating: 4.1,
    reviewsCount: 325,
    image: "https://m.media-amazon.com/images/I/81wWgct1ftL._SL1500_.jpg",
    altText: "Solimo microfiber bedsheet",
    slug: "solimo-microfiber-bedsheet"
  }
]

module.exports = sampleProducts;
